# Generated by Django 5.1.2 on 2024-11-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0002_delete_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='data',
            field=models.DateTimeField(db_comment='Date and time when the article was published'),
        ),
    ]
