# Generated by Django 5.1.2 on 2024-11-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0003_alter_historia_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
