# Generated by Django 5.1.2 on 2024-11-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0005_alter_historia_data_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='historia',
            name='categoria',
            field=models.ManyToManyField(related_name='historias', to='historias.category'),
        ),
    ]
